#!/bin/bash

# Simple i3lock command extracted from betterlockscreen
# Replace /path/to/your/wallpaper.png with your actual wallpaper path

i3lock \
    -i "/path/to/your/wallpaper.png" \
    --color "000000ff" \
    --ind-pos="x+310:y+h-80" \
    --radius=25 \
    --ring-width=5 \
    --inside-color="00000000" \
    --ring-color="ffffffff" \
    --separator-color="00000000" \
    --insidever-color="00000000" \
    --insidewrong-color="d23c3dff" \
    --ringver-color="ffffffff" \
    --ringwrong-color="ffffffff" \
    --line-uses-inside \
    --keyhl-color="d23c3dff" \
    --bshl-color="d23c3dff" \
    --clock --force-clock \
    --time-pos="ix-265:iy-10" \
    --time-align=1 \
    --time-str="%H:%M:%S" \
    --time-color="ffffffff" \
    --time-font="sans-serif" \
    --time-size=32 \
    --date-str="" \
    --greeter-pos="ix-265:iy+12" \
    --greeter-align=1 \
    --greeter-text="Type password to unlock..." \
    --greeter-color="ffffffff" \
    --greeter-font="sans-serif" \
    --greeter-size=16 \
    --layout-pos="ix-265:iy+32" \
    --layout-align=1 \
    --layout-color="ffffffff" \
    --layout-font="sans-serif" \
    --layout-size=12 \
    --verif-pos="ix+35:iy-34" \
    --verif-align=2 \
    --verif-text="Verifying..." \
    --verif-color="ffffffff" \
    --verif-font="sans-serif" \
    --verif-size=12 \
    --wrong-pos="ix+24:iy-34" \
    --wrong-align=2 \
    --wrong-text="Failure!" \
    --wrong-color="d23c3dff" \
    --wrong-font="sans-serif" \
    --wrong-size=12 \
    --modif-pos="ix+45:iy+43" \
    --modif-align=2 \
    --modif-size=12 \
    --modif-color="d23c3dff" \
    --noinput-text="" \
    --pass-media-keys \
    --pass-screen-keys \
    --pass-volume-keys \
    --pass-power-keys \
    -n