shadow = true;
shadow-radius = 48;
shadow-opacity = 1
shadow-offset-x = -48;
shadow-offset-y = -24;
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
frame-opacity = 1.0;
corner-radius = 0
blur-method = "dual_kawase"
blur-size = 20
blur-strength = 10
blur-kern = "3x3box";
backend = "glx"
dithered-present = false;
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
unredir-if-possible = true
detect-transient = true;
use-damage = true;
rules:(
@include "picom-rules.conf",
@include "picom-animations.conf"
)

